### PR TITLE
Add Options Menu

### PR DESCRIPTION
**Pull request by rayrobdod**
Not related to any formally-filed issue, but "is there a way to increase the window size" is a frequently asked question.

This PR adds a screen which allows a user to edit three `app.config` settings. The menu is accessed from a button haphazardly placed on the connect screen. The menu only responds to keyboard inputs. The three editable options are the three that involve neither key bindings nor soundtrack selection. Upon a save, the settings should both be written to `app.config` and applied to the currently-running program. Upon a cancel, no changes should occur.

I feel like this should specially-handle the case where this doesn't have permission to write to `app.config`, but I don't know what exactly it should do, so it doesn't.

### CODE REVIEW

**Comment by SapphireTactician** [comment]
@rayrobdod We have a test branch (*literally labeled `testbranch`*) that @eliatlarge hasn't merged yet but I think is safe at this point unless something caught fire in my absence that I don't know about. I honestly don't know much about how merging works but I just want to make sure your branch being behind won't mess with anything if we merge.

**Comment by SapphireTactician** [comment]
>I feel like this should specially-handle the case where this doesn't have permission to write to app.config, but I don't know what exactly it should do, so it doesn't.

@rayrobdod I'd suggest, if possible, apply the changes to the currently running instance while also displaying an error message on screen to the effect of "Changes will not persist: Config file Read-Only"

**Comment by rayrobdod** [comment]
This merges cleanly with test-branch; compiles runs everything.

The one branch I've tried that this doesn't merge cleanly with is wellme:resource-modding, but even then git managed to merge without conflicts, it's just that git doesn't realize that a few imports need to point to the resource-modding branch's new locations.

**Comment by rayrobdod** [comment]
@SapphireTactician Do you think displaying the "Changes will not persist" message in the same way as the existing "Could not connect to server" message would be sufficient?

**Comment by SapphireTactician** [comment]
@rayrobdod That would be perfect. That also reminds me, some errors messages display too briefly, so make sure it has a reasonable timeout. Perhaps 5 to 10 seconds?

**Pull request merged**
