### PR TITLE
Fix MoveCommand's use of `path`

### PR DESCRIPTION
**Pull request by rayrobdod**
Fix a regression caused in b28b490a3ae0c77740ff74346a1dca8fb40365c6 that would result in either desynchronizations or the server to crash with IndexOutOfBounds errors. See also: https://github.com/eliatlarge/FEMultiPlayer-V2/pull/148#issuecomment-362795087

### CODE REVIEW

**Comment by eliatlarge** [comment]
this seems really simple, are we going to need testing on it?

**Comment by SapphireTactician** [comment]
@rayrobdod Is this fix already applied to your `inspect-inventory` branch? (*Since I have no easy way to combine multiple branches on my end*) I was testing that and was about to report a consistent server crash at the end of Phase 1 but then I noticed this.

**Comment by rayrobdod** [comment]
This fix is not applied in `inspect-inventory`

What if I were combine the branches and push the result to a new branch and put it at https://github.com/rayrobdod/FEMultiPlayer-V2/tree/inspect-inventory-with-150

**Comment by SapphireTactician** [comment]
Sounds good, make it happen.

**Comment by rayrobdod** [comment]
Done. https://github.com/rayrobdod/FEMultiPlayer-V2/tree/inspect-inventory-with-150

**Comment by SapphireTactician** [comment]
Thanks, @eliatlarge good for merge.

**Pull request merged**
