### PR TITLE
Move cursor to lord at start of turn

### PR DESCRIPTION
**Pull request by rayrobdod**
#74, basically.

* At the start of a game, the cursor will start on the local player's lord.
  * If the player is a spectator, the cursor will still start in the upper-left corner or the map
* Add `AUTOCURSOR` option to `app.config`
  * If set to `START`, then at the start of every turn (excluding the first turn, where the start-of-game action occurs instead), then the cursor is moved to that turn's player's lord (or, more accurately the first unit in the player's list of units that is both alive and not rescued).
  * If set to `STARTLOCAL`, then the above occurs, but only at the start of the local player's turns. The cursor is not moved at the start of other player's turns.
  * If set to `OFF` (or the value is not one of the above), then the cursor is not moved involuntarily.

### CODE REVIEW

**Comment by eliatlarge** [comment]
@sapphiretactician , in your opinion, do you feel like testing these smaller pull requests to make sure there's no bugs in them that the coders missed?

**Comment by SapphireTactician** [comment]
I'll test later / tomorrow morning. Been meaning to get to it sooner but was debating True Hit and such

**Comment by SapphireTactician** [comment]
So I tested it, and these are my findings:

Default is off, that's fine.

@rayrobdod I mentioned this once in passing before and I recall you had reservations against it, but if the user already has an `app.config` file from a previous build, then the game fails to inject the file with the new settings - causing users to not know:
* The setting exists
* Where to add the new line into `app.config`

That being said, I'd like for the game to inject `app.config` with any missing lines should the user have an existing one. As it stands, I have to rename my config file, let it spawn a new one, then use that as a reference to make the needed changes to my exist one. While that's a mere nuisance for the tech savvy, it's not user friendly at all and may cause problems down the road if the user keep upgrading and letting their config file rot.  

Also, for my own future reference, @rayrobdod are the values for `app.config` settings (*as well as the setting names themselves*) case sensitive? Figured I'd save time by asking.

Other than that, it's good to go.

**Comment by rayrobdod** [comment]
The settings I've added - the enumerations - are not case sensitive; I don't know whether or not the key-bindings or music settings are case sensitive or not.

**Comment by SapphireTactician** [comment]
@rayrobdod  Oh, I forgot to mention one thing. If the Lord is rescued, and the feature is enabled, it starts on another one the player's units rather the unit the Lord is "traveling" with. Probably has to be filed as a separate PR if we want it addressed, right?

**Pull request merged**
