### PR TITLE
Rewrite handaxe animations

### PR DESCRIPTION
**Pull request by rayrobdod**
In addition to repairing handaxe animations that had been broken, this adds special support for handaxe animations: making the handaxe a separate entity from the unit throwing the handaxe and allowing handaxe animations to pause for HP depletion at either range.

### CODE REVIEW

**Comment by wellme** [comment]
There's an issue when attacking from range. The game freezes the hand axe animation on the wrong frame.

It's fine when attacking from melee range though.

**Comment by rayrobdod** [comment]
That comment caused me to look, and the paladin's hand axe attacks do the same thing - freezing at the attack animation's last frame at range and the json-declared frame at melee.

**Comment by eliatlarge** [comment]
@SapphireTactician When you get the chance, could you do a onceover of this for us? thanks

**Comment by wellme** [comment]
The handaxe animations don't quite reach all the way across the stage, making it looks like it pops in and out of existence.
image
I'm guessing that it would impossible to fix without redoing the handaxe sprites. Leaving it as is is fine though, it's not a regression and would probably be more trouble than it's worth to fix, at least for now. We should just make note to fix this in the future.

Other than that, I haven't encountered any other issues with this PR.

**Comment by rayrobdod** [comment]
Yeah, that was as much of the handaxe sprites as I could recover from the existing textures.

**Pull request merged**
