### PR TITLE
{README}[Developer contact, do not merge]

### PR DESCRIPTION
**Pull request by eliatlarge**
Hey wellme, we've noticed what you've been doing here, you've done a lot of work to fix some of the bugs we've been seeing. You don't have to do anything about this, I'm just trying to contact you (You don't have an email associated w/ your account ;-;) so we can invite you to help with the main project, if you wish.

While there haven't been any main updates, we've been discussing the direction and implementation of FEMP in the future, and we hold regular discussions [on our Discord server.](https://discord.gg/7MxggjS) If you'd lie to meet the other coders and the main fanbase of FEMP, that's where you'd want to see us.

I hope to talk to you soon!

### CODE REVIEW

**Comment by SapphireTactician** [comment]
@wellme Tagging too to help echo this. Allow me to introduce myself, I'm the volunteer QA lead for this project. I noticed some of the useful implementations you've been working on, and while I have not tested your fork at all, I feel it'd be best for the project if we work together instead of divided, and thus, like @eliatlarge has already done, I'd like to cordially invite you to join us and lend us your strength as a lot of what you've done should've been submitted as pull requests here - but I understand if you thought we abandoned it.

**Comment by eliatlarge** [comment]
@SapphireTactician he did it the absolute madman

**Comment by SapphireTactician** [comment]
Did you read his comment? He thinks the merge is probably ok. The more alarming thing is he said his fork is probably going to die soon. @wellme are you implying that you're abandoning the project altogether? We could really use your help.

**Comment by wellme** [comment]
Oh no, this should not be merged. When I said "This is probably okay-ish" in the last commit, I meant that the fork probably could be built and run as intended. The plan with this branch was to rewrite a parts of the code to make it easier to update and maintain personally. In the end, I did a lot of renaming and refactoring, changed some integer constants to enums, moved stuff to separate classes/packages, etc. I did add some features though and I will probably push them soon. Due to that, I will probably kill the branch in the near future.

**Comment by eliatlarge** [comment]
would you like me to close this then so you can do individual pull reqs later?

**Comment by wellme** [comment]
Sounds good to me

**Comment by wellme** [comment]
Poking this. @eliatlarge this PR can be closed, all (significant) changes are implemented in #136

**Pull request closed without merging**
