### PR TITLE
Insert unspecified setting values into app.config

### PR DESCRIPTION
**Pull request by rayrobdod**
No issue, but discussed [in the comments of #107](https://github.com/eliatlarge/FEMultiPlayer-V2/pull/107#issuecomment-225654132). I think elsewhere but I can't find the other ones.

### CODE REVIEW

**Comment by SapphireTactician** [comment]
I'm impressed with how well this works. Also impressed that the settings don't need to be in a specific order either as most application catch fire when their settings are out of order.

@rayrobdod Before I tag Eli for merging, is all hope lost for Eli to reverse what happened with the other commit now?

**Comment by rayrobdod** [comment]
re other commit: A squash rebase of bcb3c646c5a6ba1cee03c21f43d2efce44a3addc onto 68fa0c2656b09d1a1e9ad03807c98ed337da4ea3 is probably the easiest option at this point. [This is how one would squash rebase with the command line](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html); I don't know how or even whether it's possible to do in GitHub Desktop.

**Comment by eliatlarge** [comment]
>A word of caution: Only do this on commits that haven’t been pushed an external repository. If others have based work off of the commits that you’re going to delete, plenty of conflicts can occur. Just don’t rewrite your history if it’s been shared with others.

It looks like they should have been rebased prior to merging. now that others have the code, I don't think it's a good idea to squash.

**Comment by SapphireTactician** [comment]
@eliatlarge Considering all we're rewriting is the removal of an image no longer used, do you think it'll really cause conflicts? I'd like to think that it wouldn't, but then again, I'm not sure how Git handles such matters.

**Comment by eliatlarge** [comment]
It's just recommended practice, since git can act erratically when you do things like that. I'll keep looking into squashing, and I'll make the change if I'm able to.

**Pull request merged**
