### PR TITLE
Implement Shove and Smite

### PR DESCRIPTION
**Pull request by rayrobdod**
As per #56

### CODE REVIEW

**Comment by rayrobdod** [comment]
For the purposes of "make a topic on the sub to discuss the proposal", is hijacking https://www.reddit.com/r/FEMP/comments/4fyzlh/opinions_on_shove_smite/ sufficient?

**Comment by eliatlarge** [comment]
yeah, that's fine.

would it be too much to ask to stick this in a separate branch for *live testing* to try it separately? I'd prefer to not add anything into master unless there's full consensus/it's been tested, because clogging up the commits with add/remove makes it harder for me to log releases with what has happened. I've created [testbranch](https://github.com/eliatlarge/FEMultiPlayer-V2/tree/testbranch) for this purpose.

**Comment by SapphireTactician** [comment]
@rayrobdod I need to tell you that **I really really worded the math for Shove and Smite horribly!** The correct math is if the target's Con doesn't exceed the person shoving by more than 2. Not solely if the difference is less than 2.

**Comment by eliatlarge** [comment]
Hey, this works out since it will likely be moved anyways.

**Comment by SapphireTactician** [comment]
Moved where? I already wrote the proposal on Reddit and so far those who commented are in favor.

**Comment by eliatlarge** [comment]
I mean this commit, since massive mainstream gameplay non-balance alterations should be put into a testing branch, imo.

**Comment by rayrobdod** [comment]
I caught the con math thing.

What did was give every unit that can Smite the ability to Shove too. So, a unit can choose to Shove or Smite, and if a unit can't Smite the ability to Shove might still appear as an option. Was that wrong: should units with Smite not have the option to shove only one space?

**Comment by SapphireTactician** [comment]
>So, a unit can choose to Shove or Smite, and if a unit can't Smite the ability to Shove might still appear as an option. Was that wrong: should units with Smite not have the option to shove only one space?

You have the right idea already, if they're capable of both, they can choose either.

**Comment by SapphireTactician** [comment]
Hoping this will be merged and ready for testing soon. I can't wait to finally enjoy shoving and smiting tactics, and it looks like @eliatlarge added Console Canto since he closed it, so the riders can do their own thing. I'm psyched.

**Comment by eliatlarge** [comment]
yeah, branch testing is good. Is it sapphire's problem, or is it a missing library?

**Comment by rayrobdod** [comment]
The things in the `test` directory aren't strictly necessary for running the program. They were made to help make sure that the "real" code did what it was supposed to do, and could be used by whatever continuous integration to make sure that the primary code continues to do what it is supposed to do. However, if you are only running the program, you can safely ignore anything inside that directory.

**Comment by SapphireTactician** [comment]
Ah, ok, because the test directory existing causes me tons of compile errors due to things like `package org.junit` being missing. I'll have to remove it from my copy.

**Comment by eliatlarge** [comment]
its because of your search script, which finds *all* java files. using an IDE produces no errors for everyone else. I also am adding a line to the ant build that excludes the test dir, if that helps.

**Comment by SapphireTactician** [comment]
I don't even get as far as ant unless I remove the test directory. It fails during compile with javac. I'll just have to manually delete Test each time. :-/ No biggie, just an extra step I can add to my script.

**Comment by eliatlarge** [comment]
So, do shove and smite work as requested?

**Comment by SapphireTactician** [comment]
So far, yes, perfectly. Thank you!!! I'll know for sure once the correct Cons are implements.

**Comment by SapphireTactician** [comment]
Closed #56 as this works perfectly. (*Although I do miss the shoving sound effect from PoR and RD*) :-D Thank you so much @rayrobdod

**Pull request merged**
