### PR TITLE
Mugshot change

### PR DESCRIPTION
**Pull request by Purplemandown**
Changing the mugshot back to the subreddit one.

### CODE REVIEW

**Comment by SapphireTactician** [comment]
@eliatlarge I know it's a pain, but I heard there's a way to purge the file we're not allowed to use from both the repo and all traces of it's history. We might want to do that just to play it safe.

**Comment by rayrobdod** [comment]
As long as 9ca35093594e8af1ce23e76c5ccf31d812318cf8 remains the head commit (which is right now) a `commit --amend`, then a force push should be enough to make 9ca35093594e8af1ce23e76c5ccf31d812318cf8 effectively disappear.

@SapphireTactician Is the command that you're thinking of `git filter-branch`?

**Comment by SapphireTactician** [comment]
I think that's the one I read about, yes. Hopefully that's correct. I have like zero experience with Git

**Comment by rayrobdod** [comment]
And there goes the simple way to purge that image from the repository...

**Comment by SapphireTactician** [comment]
FML @eliatlarge You done goofed. Read comments before blindly merging.... *sigh*

**Comment by eliatlarge** [comment]
I'll make sure to do that. I think it was late. We are not distributing it though, so we aren't liable for anything.

**Comment by SapphireTactician** [comment]
True, but if we can purge it, it'd look better for us.

**Pull request merged**
