### PR TITLE
Manage CPU usage

### PR DESCRIPTION
**Pull request by rayrobdod**
- Clientside - add a configurable cap for FPS
- Serverside - make interrupt-based instead of polling-based

Related to issue #42

### CODE REVIEW

**Comment by SapphireTactician** [comment]
So I tested this from your repo, and here are my findings:

* CPU utilization is tamed by this patch
* There's noticable performance hits when playing against with a server and 2 clients on the same PC
    * I have yet to test this with two PCs running one client each
* Framerate drops to between to 7 to 5 FPS during encounters (*fight sequences*) with noticable audio stutter
    * Again, this is an observation when playing against myself on the same PC, my testing partner hasn't been available to see how this works with one client per PC.
* Framerate defaults to 30 FPS;
    * If set to 60, only one client out of the two running on the same PC can maintain it, the other wildly fluctuates between 30 to 59
* If an `app.config` file already exists from a previous build, it won't inject the new settings, using what I'd presume are just the defaults.

**Comment by rayrobdod** [comment]
Interesting: in my experience the fight scenes have had a slightly better performance than the overworld stage, and in neither case does either plummet like that.

**Comment by eliatlarge** [comment]
perhaps we should wait for testing on other PCs before merging

**Comment by SapphireTactician** [comment]
>Interesting: in my experience the fight scenes have had a slightly better performance than the overworld stage, and in neither case does either plummet like that.

I have a feeling you're tests are with the default scaling of `SCALE=1.0`, correct? Despite my bad eyesight, I tested it with this myself and the performance hits aren't nearly as pronounced, which is probably why you didn't observe the issues I reported. Try setting `SCALE=` to `2.0` on your end and see if the performance hit during fight scenes is noticably worse, or if my PC is just a potato despite its stats.

**Comment by rayrobdod** [comment]
I had been running at SCALE=1.0 and two clients on the same machine, but even at SCALE=2.0, or even SCALE=1.5, I find no significant performance drops.

If the two games are using all availiable CPU, I have also noticed one game running near the FPS cap and the other below that. The CPU scheduler on my computer seems to favor the window with input focus; the active window is the one running at a higher FPS. Which I like, and the CPU scheduler is an OS component.

**Comment by rayrobdod** [comment]
I had been running at SCALE=1.0 and two clients on the same machine, but even at SCALE=2.0, or even SCALE=1.5, I find no significant performance drops.

If the two games are using all availiable CPU, I have also noticed one game running near the FPS cap and the other below that. The CPU scheduler on my computer seems to favor the window with input focus; the active window is the one running at a higher FPS. Which I like, and the CPU scheduler is an OS component.

**Comment by rayrobdod** [comment]
I had been running at SCALE=1.0 and two clients on the same machine, but even at SCALE=2.0, or even SCALE=1.5, I find no significant performance drops.

If the two games are using all availiable CPU, I have also noticed one game running near the FPS cap and the other below that. The CPU scheduler on my computer seems to favor the window with input focus; the active window is the one running at a higher FPS. Which I like, and the CPU scheduler is an OS component.

**Comment by rayrobdod** [comment]
I had been running at SCALE=1.0 and two clients on the same machine, but even at SCALE=2.0, or even SCALE=1.5, I find no significant performance drops.

If the two games are using all availiable CPU, I have also noticed one game running near the FPS cap and the other below that. The CPU scheduler on my computer seems to favor the window with input focus; the active window is the one running at a higher FPS. Which I like, and the CPU scheduler is an OS component.

**Comment by SapphireTactician** [comment]
I see. I have a feeling this boils down to hardware as your PC is far superior than mine (*iirc, you once said your's is a quad-core, whereas mine is only a dual-core; I'd assume your GPU is superior as well*). As for the CPU scheduler, I'm running Linux primarily, and it's CPU scheduler, to my understanding, prefers to distribute favor evenly amongst all running processes except for a few important system processes as defined by the distribution unless manually changed via the `nice` command which I think only applies to that particular instance of the process and doesn't persist. That said, when testing the performance, I have no other applications open usually.

Is there anything that can be done? Or are entry level / economy PCs with two cores and 8gb of ram just shit out of luck? :-/

**Comment by rayrobdod** [comment]
I have 4GB of ram, so I take offense to that last one. And comparing a quad-core at 1.8 GHz to a dual core at 3.0 GHz… not the point

I thought Linux reduced the priority of processes that took up their entire allotted time slot before yielding. Or, I guess at least part of it.

* Is the slowdown during fights a regression, or does it also exist in master?
* Does CPU return to 50% per process during fight scenes?
* Are certain battle scenes worse than others? I'm thinking specifically some of the large magic effects like ereshkigal.

**Comment by SapphireTactician** [comment]
>I have 4GB of ram, so I take offense to that last one.

No offense intended, I just assumed mine was an economy / entry level PC because 1.) It's eMachines brand, and 2.) I bought it 5 yrs ago for only $200.

>And comparing a quad-core at 1.8 GHz to a dual core at 3.0 GHz… not the point

You never told me the clock speed of yours, only that it was quad-core. I'd still think more cores are better even if the clock speed was lower, but perhaps that's dependent on if the application supports multi-threading and such.

>I thought Linux reduced the priority of processes that took up their entire allotted time slot before yielding. Or, I guess at least part of it.

To be honest, I'm not entirely sure of the inner workings as I haven't looked too much into it. Like I said, I could be completely wrong, but what little I read states that it uses something known as the Completely Fair Scheduler, which tends to distribute priority as evenly as possible within the set group's alloted resources (*System / Root, User - the group FEMP would belong to, etc.*).

>Is the slowdown during fights a regression, or does it also exist in master?
Bare in mind that the following answers are observed when playing against myself and running 2 clients and the server on the same PC. These probably won't be observed under normal single client usage (*which I'll try to test tonight, assuming my partner's crappy internet is willing*).

It exists in both; but with some key differences between Master and your framerate branch

**Framerate Branch:**

* Only certain fights experience slowdown, as opposed to all, if `SCALE=1.0`
* Slowdown during fights in universally, and significantly, worse with `SCALE=2.0`
* If slowdown is significant, audio will stutter
* CPU utilization spikes to the same amount as Master's CPU utilization % only during observed slowdowns

**Master:**

* All fights experience slowdown regardless of scaling
* Severity varies based on scaling
* At `SCALE=2.0` roughly half the frames are dropped
* Audio doesn't stutter regardless of slowdown

>Does CPU return to 50% per process during fight scenes?

The CPU spike occurs only during certain fight scenes (*if `SCALE=1.0`*) and all if `SCALE=` is set higher, `2.0` specifically. Now here's where it gets interesting, regardless of scale, the spike also occurs during the transition between scenes.

>Are certain battle scenes worse than others? I'm thinking specifically some of the large magic effects like ereshkigal.

Oddly enough, the framerate drops are only observed during the transition between the overworld and the battle scenes, and only during battles involving units with longer / more complex attack animations (*such as Pegasi, Swordmasters when Astra activates, Snipers, etc.*). Magic animations, including Ereshkigal, didn't observe any CPU spike or framerate hit.

Weird, huh?

**Comment by rayrobdod** [comment]
I probably should have thought to ask for the big guns sooner.

Basically, what I want you to do is find CPU hotspots using `jvisualvm` (which should be included with the jdk; you did end up with the jdk, right?). I don't know how obvious jvisualvm's interface is, but the steps are

1. Open both jvisualvm and the FEMPs
2. In jvisualvm, select  `net.fe.FEMultiplayer` (either one) in the left panel, then the `Sampler` tab.
3. in FEMP proceed until just before one of the battles that experiences slowdown
4. in jvisualvm, select the `CPU` button to begin the CPU sampling
5. In FEMP, let the fight scene play out
6. In jvisualvm press the Snapshot button, and a snapshot should open in a new tab.
7. Interpret, which in this case probably means "export the snapshot to a "Profiler Snapshot File" and upload that file so I may look at it" :sweat_smile:

At this point my theory involves the sprite recoloring, and there's probably more targeted experiments that could be done, but if you can use jvisualvm, I'd rather see the results of general profiling.

When I tried it: the results showed that `FightStage.render()` was consistently split into approximately 50% `Healthbar.render()`, 10-to-30% `anim.HUD.render()`, and the rest. And that overall `org.lwjgl.opengl.ARBShaderObjects.nglUseProgramObjectARB[native]` (Which I think is the execution of the shaders, including the pallet swap) had a higher self-time when two swordmasters critted eachother than when two Hectors attacked eachother.

**Comment by SapphireTactician** [comment]
Looks like VisualVM is distributed as a separately from OpenJDK, just installed it now.

>I probably should have thought to ask for the big guns sooner.

You know, the best part of Quality Assurance work is hunting for deer with a bazooka. Love knowing such toys exist, I'm on it! :-D Hopefully I can dig up something fun for you. I'm going to get these samples for you on both scales because I'm curious why it's downright crippling on the higher scale.

**Comment by SapphireTactician** [comment]
Idk why but I'm getting totally different results, at least with the Pegasi battles. Wish I had a debug weapon with 100 Crit so I can snapshot Swordmaster crits and Astra.

I should note that some FPS drops may be false positives because the animation speed seems normal sometimes despite the FPS counter reporting a low number.

Here's your snapshots btw:

[FEMP_FrameRateBranch_Snapshots.zip](https://github.com/eliatlarge/FEMultiPlayer-V2/files/260524/FEMP_FrameRateBranch_Snapshots.zip)

**Comment by rayrobdod** [comment]
> Wish I had a debug weapon with 100 Crit 

Each weapon's crit (among other things) is stored in [/res/weapons.txt](https://github.com/eliatlarge/FEMultiPlayer-V2/blob/master/res/weapons.txt). Weapons won't appear in the shop if their cost is 1G or they have "Debug" in the name. Have fun.

> animation speed seems normal sometimes despite the FPS counter reporting a low number.

Most animations change based on delta time, not frame count. Even the raster animations.

> snapshots

I'm rather amazed at how large SwapBuffers' proportion is. Maybe that implementation of OpenGL is buffering or otherwise doing its thing lazily? I don't know what to make of it.

**Comment by SapphireTactician** [comment]
The other thing that stuck out is how large `java.io.ObjectInputStream.readObject()` 's proportion is as well. Is that normal?

As for OpenGL, I have no idea. If my graphic drivers have anything to do with it, for reference, I am using Nvidia's proprietary Linux legacy drivers since the open source drivers didn't support my graphics chipset well at all, at least on Debian 8 anyways.

>Have fun.

Ooooh, looking forward to it. I'll get on in the morning and gather Swordmaster snapshots to see how / if they differ from the Pegasi ones. It's 3:20am already. Time goes by too fast.

**Comment by rayrobdod** [comment]
There is one thread whose sole purpose in life is waiting to receive stuff from the network. That's represented by the `ObjectInputStream.readObject()`, although it is odd that its reported as CPU time instead of Waiting-on-Monitor time.

**Comment by SapphireTactician** [comment]
So I did more snapshots; Prompted by the OpenGL anomaly you pointed out, I did a set in Windows 7 as well on the same PC. Here's where things get really intriguing; compare the first zip's `SCALE=1.0` snapshot (*which is also in the new Linux snapshot zip: labeled as `FEMP_FrameRateBranch_Pegasi_Scale1-0_FPS60.nps`*) to the Windows Pegasi snapshot. You'll notice that instead of SwapBuffers, the largest proportion is (*if I'm reading and following this tree correctly*) the `Self Time` of `org.newdawn.slick.opengl.PNGDecoder.decode()`

Then when comparing the Linux Swordmaster snapshot to the Windows Swordmaster snapshot, well, I have absolutely no idea what to make of this one, because unlike the Linux vs. Windows Pegasi comparison, they both seem to dump most of the CPU time into SwapBuffers like how Linux did in all snapshots.  
  
Any other test(*s*) I can / should perform with (*J*)VisualM?

*****

### Snapshots:

[FEMP_FrameRateBranch_Linux_Snapshots.zip](https://github.com/eliatlarge/FEMultiPlayer-V2/files/261799/FEMP_FrameRateBranch_Linux_Snapshots.zip)
[FEMP_FrameRateBranch_Windows_Snapshots.zip](https://github.com/eliatlarge/FEMultiPlayer-V2/files/261800/FEMP_FrameRateBranch_Windows_Snapshots.zip)

**Comment by rayrobdod** [comment]
I got nothin.

**Comment by SapphireTactician** [comment]
That's.... not good. What do we do?

**Comment by SapphireTactician** [comment]
Well, it seems pretty clear that the culprit is Slick2D, especially with the high self-time, and the more I read about it and the fact it's no longer maintained, the more damning it looks. Everything I've read suggests we migrate to LibGDX. Forums go as far as calling Slick2D "Dead, and buggy. A lackluster library compared to LibGDX."

**Comment by eliatlarge** [comment]
Well, this project was started in like 2011. short of reforming the engine, we'll just have to live with it. Once everything gets done, if this is still a major issue then we might be able to do something about it.

@rayrobdod , does this branch still do the slowdown on the animations?

**Comment by SapphireTactician** [comment]
>@rayrobdod , does this branch still do the slowdown on the animations?

Yes, and he said he doesn't have any idea for what can be done. Which is why I'm suggesting we migrate to a library better suited for this. Please don't dismiss what I say simply because I'm not a programmer, the library we're using is abandoned for a reason.

>if this is still a major issue then we might be able to do something about it.

It's a major issue now that we need to address now because while it's not a fatal error, it's crippling enough to make it near unplayable; My CPU is being hammered so hard testing is a complete chore. This branch helps only when there's no scaling (*which isn't very beneficial cause even the sub says the default scale is too small to play comfortably*), with increased scaling, such as `SCALE=2.0` the situation is worsened considerably during combat sequences. -_-

**Comment by eliatlarge** [comment]
I'm not writing you off, I had no idea how bad it was for you. Its just that, if we were to migrate, it would require my complete attention and prevent us from having any new content for a *very* long time. That said, while I can't mess with the main game, if you want I could make a secondary branch for you that uses this commit, and then you can make duplicates of it and pull whatever branches you want to test from other locations.

**Comment by SapphireTactician** [comment]
> if you want I could make a secondary branch for you that uses this commit,  
  
I'd say that'd help but again, this branch only really helps (*at least when running the server and 2 clients on the same PC*) with the default scaling `SCALE=1.0` but as I have said before (*and I think the sub will back me up on this one*) 480x320, especially on a 1600x900 display, is way too small and causes a lot of eye strain. When the scale is doubled to `SCALE=2.0`, this branch performs worse than Master most of the time with an even lower framer and audio stutter. (*Again, this is in regards to running 2 clients and a server on a single PC*) It's a no-win situation for me. I even tried with Windows, (*as you've seen in the snapshot files*) to no avail.

Unless @rayrobdod can figure something out, I'm not sure what else can be done. Everything I've read simply says the Slick2D libraries are just that painfully bad. Meanwhile I've just been painfully tolerating the system slowdown while accepting that I can't multi-task, at all, during testing.

**Comment by rayrobdod** [comment]
> @rayrobdod , does this branch still do the slowdown on the animations?

With what was submitted, I don't experience either `scale=2.0` or fightstage related excessive CPU, and that was true before I submitted it. So, I'm not the one to ask about whether the branch still producing slowdown.

Actually, @eliatlarge, have you tried this branch?

**Comment by SapphireTactician** [comment]
>With what was submitted, I don't experience either scale=2.0 or fightstage related excessive CPU, and that was true before I submitted it. So, I'm not the one to ask about whether the branch still producing slowdown.

Unless there's a new build of the framerate branch since my last series of profiler snapshots, then I'm still experiencing slowdown and FPS plummets.

@rayrobdod so at `SCALE=2.0` and the FPS set to 60 (*especially though I'm observing it even at 30 - just not as crippling*), you're not experiencing any hard framerate drops? I swear those two extra cores, even if they are slower than mine, are making a difference.

**Comment by rayrobdod** [comment]
To the point where the Fight Stage often can reach 60FPS even in situations where the Overworld Stage could not. Like, the one I just tried with two instances both set to use only one core and the same core at that, the Overworld stage was hovering in the mid 20s, and the fight stage was high 50s. And the hot spot was still `ARBShaderObjects.glUseProgramObjectARB`, not `Implementation.swapBuffers`.

[Profiler Snapshot of that instance](https://github.com/eliatlarge/FEMultiPlayer-V2/files/274058/femp_rrd_scale2.0_falcon_60fps.nps.zip), because the attempts to make a video recording ended up at 3 frames per minute.

**Comment by rayrobdod** [comment]
Regarding switching libGDX: the odd thing about FEMP is that there's no concept of model-view separation, and yet for the most part, the stuff in `net.fe` depends on `chu.engine` which depends on slick, but `net.fe` does not depend on slick. The former complicates a change; the later eases it; I don't know which would dominate.

**Comment by eliatlarge** [comment]
>no concept of model-view separation

Could you clarify this? Do you mean that sprites should be controlled independently, rather than being made to update themselves?

**Comment by SapphireTactician** [comment]
@rayrobdod your pegasi snapshot is radically different from mine, it's even mentioning threads that mine did. I took the liberty of clicking the Info tab on your snapshot and there's settings you didn't instruct me to use at all, rather, you had me blindly go in there with just the defaults.

Yours:

    Settings Name: Analyze Performance
    Profiling Type: CPU Profiling (Entire Application)
    
    Root Methods: net.fe.**.*()
    CPU Profiling Type: Instrumentation
    CPU Timer: Off
    Exclude time spent in Thread.sleep() and Object.wait(): Yes
    Limit number of profiled threads: 32
    Instrumentation Filter: java.*, javax.*,sun.*, sunw.*, com.sun.*
    Instrumentation Scheme: Lazy
    Instrument Method Invoke: Yes
    Instrument New Threads: Yes
    Instrument Getters and Setters: No
    Instrument Empty Methods: N

Vs. mine:

    Settings Name: Analyze Performance
    Profiling Type: CPU Profiling (Sampling Application)
    
    CPU Profiling Type: Sampled
    Sampling Period: 10 ms
    Instrumentation Filter: 

Looks like I'm going to have to harvest new snapshots. Joy...

**Comment by rayrobdod** [comment]
Okay, technically what I provided was a Profiler snapshot, not a Sampler snapshot. The difference is that the Profiler is more detailed, but will modify classes to make that possible and will half the time not work at all. Which is why my instructions said "use the sampler"; the sampler will always work and is detailed enough in almost all cases. I should have known not to deviate from my instructions.

AMD-A6-6310. That's what Device manager is telling me; I don't know any details about memory sharing or whatever. But that's not the point.

**Comment by SapphireTactician** [comment]
>Shared vs. Dedicated

Massive performance difference.

Dedicated = Graphics chipset has it's own independent processor (*GPU*) and Video RAM

Shared = Most onboard / intergrated graphics cards; System CPU and reserved portion of System RAM perform all the graphics processing.

**Comment by eliatlarge** [comment]
so the question stands, does this commit make the game more/less playable for slower computers? this conversation isn't really going anywhere (mostly my fault) and it doesn't impact high spec comps so I just want to know if this, albeit with a slowdown, is acceptable until we can find the time to redo the engine.

**Comment by SapphireTactician** [comment]
>so the question stands, does this commit make the game more/less playable for slower computers?

@eliatlarge it's not so black and white is what we're getting at. I wish it was, but it's not. This is a complex issue requiring a complex solution. It's not even about speed so much as hardware functionality overall in regards to systems with Shared resources versus Dedicated resources.

To answer your question, for a system with Shared resources, the playability is significantly worse to the point it is nearly unplayable ONLY during both scene transitions and combat sequences, **the moment scaling is utilized. Something most people tend to adjust due to how small the default 320x480 resolution is on modern displays.** It does make the overworld more playable in most cases. @rayrobdod isn't observing any issues because he most likely is using an aftermarket, dedicated, graphics card that doesn't tax the system's CPU or RAM.

The solution to this is to continue tweaking this branch in order to improve the game's overall efficiency which may or may not involve overhauling our graphical libraries. It works in some cases, but makes things worse in others. It has merit, but I wouldn't merge it yet.

**Comment by rayrobdod** [comment]
I know what the difference between Dedicated and Shared memory is. That doesn't help me discover the architecture of my computer's CPU/GPU/whatever chips. What would help me discover the architecture is either a better internet search query or a microscope.

**Comment by SapphireTactician** [comment]
Oh, I must've misread. Well, a quick internet search tells me the following about your system (*I think I pulled the right mobo specs - though it would've been easier to just search the computer's brand and model number*)

If I'm reading this correctly, it's a laptop with a Radeon R4 integrated chipset. However, what complicates things is that you have a new type of CPU invented by AMD, known as an APU (*AMD Accelerated Processor Unit*) which is a specialized CPU engineered specifically for the purpose of doing both everyday processing and graphical processing on a single chip. Meaning that even though your system is sharing RAM (*which hurts performance a little*), it has a processor geared specifically for being shared without any of the drawbacks.

Older AMD PCs without APUs and all Intel users with integrated graphics are still out in the cold.

**Comment by rayrobdod** [comment]
And somehow this laptop cost approximately an arm and two legs less than a PS4… I'll just accept that I got more than I paid for.

**Comment by SapphireTactician** [comment]
lol, by like, I meant the same technology, PS4 has way more cores.

**Comment by SapphireTactician** [comment]
This PR has been deadlocked for some time now. I'm going to close this because A.) at least on standard non-APU configurations, there cons outweigh the pros on any setup other than `Scale=1.0` and B.) It'll be a non-issue (*I hope*) once we migrate to LibGDX.

Let's focus on fixing the connectivity issues for now, but I have no objections to reopening this PR if a breakthrough can be made somehow.

**Pull request closed without merging**
