### PR TITLE
Make handaxes use handaxe animation even in melee range

### PR DESCRIPTION
**Pull request by rayrobdod**
For issue #114

### CODE REVIEW

**Comment by eliatlarge** [comment]
@SapphireTactician would you like to test this?

**Comment by SapphireTactician** [comment]
I'd like to just say go ahead but it seems to rewrite a few other areas, so I'd like to give it a quick once-over tomorrow if that's ok.

**Comment by eliatlarge** [comment]
That's fine, I'll merge when you give the OK

**Comment by SapphireTactician** [comment]
[I experienced a softlock while testing this.](https://github.com/eliatlarge/FEMultiPlayer-V2/issues/115#issuecomment-227913674) I'll need more time to determine if the incident is related to this PR or not.

**Comment by SapphireTactician** [comment]
@eliatlarge I think it's okay to merge. I believe the softlock is unrelated to the PR and more to do with some fundamental difference between playing a LAN game via `localhost` and a WAN game (*especially against yourself*) via typing in your public IP address.

**Pull request merged**
